name: Publish Package
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: yarn install
    - name: Configure CI Git User
      run: |
        git config --local user.name 'GitHub Action'
        git config --local user.email 'action@github.com'
    - name: Configure .npmrc
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        npm whoami
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish
      run: |
        yarn lerna publish --create-release=github --yes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
